import 'dart:ui';
import 'package:flutter/material.dart';
import '../../models/knobs.dart';
import '../../models/widget_info.dart';

final List<WidgetInfo> effectsWidgets = [
  WidgetInfo(
    name: 'ShaderMask',
    description:
        'A widget that applies a mask generated by a shader to its child.',
    category: WidgetCategory.effects,
    builder: (context) => ShaderMask(
      shaderCallback: (Rect bounds) {
        return const RadialGradient(
          center: Alignment.topLeft,
          radius: 1.0,
          colors: <Color>[Colors.yellow, Colors.deepOrange],
          tileMode: TileMode.mirror,
        ).createShader(bounds);
      },
      child: const Text(
        'I am burning the memories',
        style: TextStyle(color: Colors.white, fontSize: 24),
      ),
    ),
    codeSnippet: '''
ShaderMask(
  shaderCallback: (Rect bounds) {
    return const RadialGradient(
      center: Alignment.topLeft,
      radius: 1.0,
      colors: <Color>[Colors.yellow, Colors.deepOrange],
      tileMode: TileMode.mirror,
    ).createShader(bounds);
  },
  child: const Text(
    'I am burning the memories',
    style: TextStyle(color: Colors.white, fontSize: 24),
  ),
)
''',
  ),
  WidgetInfo(
    name: 'Opacity',
    description: 'A widget that makes its child partially transparent.',
    category: WidgetCategory.effects,
    playground: WidgetPlayground(
      knobs: const [
        DoubleKnob('opacity', 'Opacity', min: 0, max: 1, initial: 0.5),
      ],
      builder: (context, k) => Opacity(
        opacity: k.number('opacity'),
        child: Container(
          width: 120,
          height: 120,
          color: Colors.red,
          child: Center(child: Text('${(k.number('opacity') * 100).round()}%')),
        ),
      ),
    ),
    builder: (context) => Opacity(
      opacity: 0.5,
      child: Container(
        width: 100,
        height: 100,
        color: Colors.red,
        child: Center(child: Text('50% Opacity')),
      ),
    ),
    codeSnippet: '''
Opacity(
  opacity: 0.5,
  child: Container(
    width: 100,
    height: 100,
    color: Colors.red,
    child: Center(child: Text('50% Opacity')),
  ),
)
''',
  ),
  WidgetInfo(
    name: 'ColorFiltered',
    description: 'A widget that applies a ColorFilter to its child.',
    category: WidgetCategory.effects,
    builder: (context) => ColorFiltered(
      colorFilter: const ColorFilter.mode(Colors.grey, BlendMode.saturation),
      child: Image.network(
        'https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg',
        width: 200,
        height: 200,
        fit: BoxFit.cover,
        errorBuilder: (context, error, stackTrace) => Container(
          width: 200,
          height: 200,
          color: Colors.blue,
          alignment: Alignment.center,
          child: const Text(
            'Image Placeholder',
            style: TextStyle(color: Colors.white),
          ),
        ),
      ),
    ),
    codeSnippet: '''
ColorFiltered(
  colorFilter: const ColorFilter.mode(Colors.grey, BlendMode.saturation),
  child: Image.network(
    'https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg',
    width: 200,
    height: 200,
    fit: BoxFit.cover,
  ),
)
''',
  ),
  WidgetInfo(
    name: 'ImageFiltered',
    description: 'A widget that applies an ImageFilter to its child.',
    category: WidgetCategory.effects,
    builder: (context) => ImageFiltered(
      imageFilter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
      child: Image.network(
        'https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg',
        width: 200,
        height: 200,
        fit: BoxFit.cover,
        errorBuilder: (context, error, stackTrace) => Container(
          width: 200,
          height: 200,
          color: Colors.red,
          alignment: Alignment.center,
          child: const Text(
            'Image Placeholder',
            style: TextStyle(color: Colors.white),
          ),
        ),
      ),
    ),
    codeSnippet: '''
// Requires import 'dart:ui';
ImageFiltered(
  imageFilter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
  child: Image.network(
    'https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg',
    width: 200,
    height: 200,
    fit: BoxFit.cover,
  ),
)
''',
  ),
  WidgetInfo(
    name: 'Banner',
    description: 'A widget that displays a diagonal message at a corner.',
    category: WidgetCategory.effects,
    builder: (context) => Container(
      margin: const EdgeInsets.all(10.0),
      color: Colors.yellow,
      height: 100,
      width: 200,
      child: Banner(
        message: 'New!',
        location: BannerLocation.topEnd,
        color: Colors.red,
        child: Container(
          color: Colors.amber,
          height: 100,
          width: 200,
          child: const Center(child: Text('Banner Example')),
        ),
      ),
    ),
    codeSnippet: '''
Banner(
  message: 'New!',
  location: BannerLocation.topEnd,
  color: Colors.red,
  child: Container(
    color: Colors.amber,
    height: 100,
    width: 200,
    child: const Center(child: Text('Banner Example')),
  ),
)
''',
  ),
  WidgetInfo(
    name: 'Magnifier',
    description: 'A widget that magnifies the content beneath it.',
    category: WidgetCategory.effects,
    builder: (context) => Stack(
      alignment: Alignment.center,
      children: [
        const Text('Hover/Drag to magnify! (Implementation simulated here)'),
        RawMagnifier(
          decoration: const MagnifierDecoration(
            shape: CircleBorder(
              side: BorderSide(color: Colors.black, width: 2),
            ),
          ),
          size: const Size(100, 100),
          magnificationScale: 2,
          child: Container(),
        ),
      ],
    ),
    codeSnippet: '''
// Usually used with a breakdown of gesture detectors or overlay
RawMagnifier(
  decoration: const MagnifierDecoration(
    shape: CircleBorder(
      side: BorderSide(color: Colors.black, width: 2),
    ),
  ),
  size: const Size(100, 100),
  magnificationScale: 2,
)
''',
  ),
];
